import type { components } from '@/api/generated/schema.js'

export type CapabilitiesV2Envelope = components['schemas']['Capabilities']
export type AuditResultV2 = components['schemas']['AuditResultV2']
export type PostTrainingV2Capability = components['schemas']['PostTrainingV2Capability']
export type DatasetManifestV2 = components['schemas']['DatasetManifestV2']
export type DatasetViewV2 = components['schemas']['DatasetViewV2']
export type RefMetadataV2 = components['schemas']['RefMetadataV2']
export type RefPageV2 = components['schemas']['RefPageV2']
export type RecordEligibilityV2 = components['schemas']['RecordEligibilityV2']
export type RecordPageV2 = components['schemas']['RecordPageV2']
export type RecordSummaryV2 = components['schemas']['RecordSummaryV2']
export type RecordViewV2 = components['schemas']['RecordViewV2']
export type PostTrainingRecordV2 = components['schemas']['PostTrainingRecordV2']
export type RecordContentV2 = PostTrainingRecordV2['contents'][number]
export type RecordPartV2 = RecordContentV2['parts'][number]
export type CandidateV2 = PostTrainingRecordV2['candidates'][number]
export type SignalV2 = CandidateV2['signals'][number]
export type PreferenceRelationV2 = PostTrainingRecordV2['preference_relations'][number]
